<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- macOS/Linux 上でも net8.0-windows (WPF) プロジェクトをコンパイルできるようにする -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <Product>KeyDisp for Windows</Product>
    <Copyright>© 2026 con3code</Copyright>
  </PropertyGroup>
</Project>
